################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
OBJ_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
C++_DEPS := 
OBJS := 
C_DEPS := 
CC_DEPS := 
CPP_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
utils \
src/wimax/test \
src/wimax/model \
src/wimax/helper \
src/wimax/examples \
src/wifi/test \
src/wifi/model \
src/wifi/helper \
src/wifi/examples \
src/visualizer/model \
src/virtual-net-device/model \
src/virtual-net-device/examples \
src/uan/test \
src/uan/model \
src/uan/helper \
src/uan/examples \
src/topology-read/test \
src/topology-read/model \
src/topology-read/helper \
src/topology-read/examples \
src/tools/test \
src/tools/model \
src/tools/examples \
src/test \
src/test/perf \
src/test/ns3wifi \
src/test/ns3tcp \
src/tap-bridge/model \
src/tap-bridge/helper \
src/tap-bridge/examples \
src/stats/test \
src/stats/model \
src/spectrum/test \
src/spectrum/model \
src/spectrum/helper \
src/spectrum/examples \
src/propagation/test \
src/propagation/model \
src/propagation/examples \
src/point-to-point-layout/model \
src/point-to-point/test \
src/point-to-point/model \
src/point-to-point/helper \
src/point-to-point/examples \
src/openflow/test \
src/openflow/model \
src/openflow/helper \
src/openflow/examples \
src/olsr/test \
src/olsr/model \
src/olsr/helper \
src/olsr/examples \
src/nix-vector-routing/model \
src/nix-vector-routing/helper \
src/nix-vector-routing/examples \
src/network/utils \
src/network/test \
src/network/model \
src/network/helper \
src/network/examples \
src/netanim/test \
src/netanim/model \
src/netanim/helper \
src/netanim/examples \
src/mpi/model \
src/mpi/examples \
src/mobility/test \
src/mobility/model \
src/mobility/helper \
src/mobility/examples \
src/mesh/test \
src/mesh/test/flame \
src/mesh/test/dot11s \
src/mesh/model \
src/mesh/model/flame \
src/mesh/model/dot11s \
src/mesh/helper \
src/mesh/helper/flame \
src/mesh/helper/dot11s \
src/mesh/examples \
src/lte/test \
src/lte/model \
src/lte/helper \
src/lte/examples \
src/internet/test \
src/internet/model \
src/internet/helper \
src/internet/examples \
src/flow-monitor/test \
src/flow-monitor/model \
src/flow-monitor/helper \
src/energy/test \
src/energy/model \
src/energy/helper \
src/energy/examples \
src/emu/model \
src/emu/helper \
src/emu/examples \
src/dsr/test \
src/dsr/model \
src/dsr/helper \
src/dsr/examples \
src/dsdv/test \
src/dsdv/model \
src/dsdv/helper \
src/dsdv/examples \
src/csma-layout/model \
src/csma-layout/examples \
src/csma/model \
src/csma/helper \
src/csma/examples \
src/core/test \
src/core/model \
src/core/examples \
src/core/bindings \
src/config-store/model \
src/config-store/examples \
src/click/test \
src/click/model \
src/click/helper \
src/click/examples \
src/buildings/test \
src/buildings/model \
src/buildings/helper \
src/buildings/examples \
src/bridge/model \
src/bridge/helper \
src/bridge/examples \
src/applications/test \
src/applications/model \
src/applications/helper \
src/aodv/test \
src/aodv/model \
src/aodv/helper \
src/aodv/examples \
src/antenna/test \
src/antenna/model \
scratch/subdir \
scratch \
examples/wireless \
examples/udp-client-server \
examples/udp \
examples/tutorial \
examples/tcp \
examples/stats \
examples/socket \
examples/routing \
examples/realtime \
examples/naming \
examples/mobility \
examples/matrix-topology \
examples/ipv6 \
examples/error-model \
examples/energy \
build/utils \
build/src/wimax/model \
build/src/wimax/helper \
build/src/wifi/model \
build/src/wifi/helper \
build/src/virtual-net-device/model \
build/src/uan/model \
build/src/uan/helper \
build/src/topology-read/model \
build/src/topology-read/helper \
build/src/tools/model \
build/src/tap-bridge/model \
build/src/tap-bridge/helper \
build/src/stats/model \
build/src/spectrum/model \
build/src/spectrum/helper \
build/src/propagation/model \
build/src/point-to-point-layout/model \
build/src/point-to-point/model \
build/src/point-to-point/helper \
build/src/olsr/model \
build/src/olsr/helper \
build/src/nix-vector-routing/model \
build/src/nix-vector-routing/helper \
build/src/network/utils \
build/src/network/model \
build/src/network/helper \
build/src/netanim/model \
build/src/netanim/helper \
build/src/mpi/model \
build/src/mobility/model \
build/src/mobility/helper \
build/src/mesh/model \
build/src/mesh/model/flame \
build/src/mesh/model/dot11s \
build/src/mesh/helper \
build/src/mesh/helper/flame \
build/src/mesh/helper/dot11s \
build/src/lte/model \
build/src/lte/helper \
build/src/internet/model \
build/src/internet/helper \
build/src/flow-monitor/model \
build/src/flow-monitor/helper \
build/src/energy/model \
build/src/energy/helper \
build/src/emu/model \
build/src/emu/helper \
build/src/dsr/model \
build/src/dsr/helper \
build/src/dsdv/model \
build/src/dsdv/helper \
build/src/csma-layout/model \
build/src/csma/model \
build/src/csma/helper \
build/src/core/model \
build/src/config-store/model \
build/src/buildings/model \
build/src/buildings/helper \
build/src/bridge/model \
build/src/bridge/helper \
build/src/applications/model \
build/src/applications/helper \
build/src/aodv/model \
build/src/aodv/helper \
build/src/antenna/model \
build/scratch/subdir \
build/scratch \
build/.conf_check_fe0ca542f39064c5a14ee41a2e983996/testbuild \
build/.conf_check_fe0ca542f39064c5a14ee41a2e983996 \
build/.conf_check_fc0bab0b855f90bf0795892663948c43/testbuild \
build/.conf_check_fc0bab0b855f90bf0795892663948c43 \
build/.conf_check_e2bf758aaca47858b67848f504a8de27/testbuild \
build/.conf_check_e2bf758aaca47858b67848f504a8de27 \
build/.conf_check_d8a2c40aecfb7c8eac7dd03fcbfb1110/testbuild \
build/.conf_check_d8a2c40aecfb7c8eac7dd03fcbfb1110 \
build/.conf_check_d6c8946949ece91ce43c989711393fec/testbuild \
build/.conf_check_d6c8946949ece91ce43c989711393fec \
build/.conf_check_cc227f9b4319ad1c726eca4fb806395e/testbuild \
build/.conf_check_cc227f9b4319ad1c726eca4fb806395e \
build/.conf_check_c59373285bc13999c3df79164cb29af1/testbuild \
build/.conf_check_c59373285bc13999c3df79164cb29af1 \
build/.conf_check_c4081480d4a9d97f4ed31819aee44093/testbuild \
build/.conf_check_c4081480d4a9d97f4ed31819aee44093 \
build/.conf_check_9a9aa0a48a7447bdd461f06307f32dc7 \
build/.conf_check_703a8a276d4ad265d967b1b45f1fc578 \
build/.conf_check_591f7be6a22ba3cd4f507fd8bc09bd2a/testbuild \
build/.conf_check_591f7be6a22ba3cd4f507fd8bc09bd2a \
build/.conf_check_39b3cecfac3989b2ed760243cef109e6/testbuild \
build/.conf_check_39b3cecfac3989b2ed760243cef109e6 \
build/.conf_check_38008f7ca978e5462e378992d39050f1/testbuild \
build/.conf_check_38008f7ca978e5462e378992d39050f1 \
build/.conf_check_2ca1edb217ad9cef6c81468eb5adffbb \
build/.conf_check_2be466e82e703a744ee152afe2b58299/testbuild \
build/.conf_check_2be466e82e703a744ee152afe2b58299 \
build/.conf_check_29f41b0aad55c9546dfc9b7ce9859059/testbuild \
build/.conf_check_29f41b0aad55c9546dfc9b7ce9859059 \
build/.conf_check_293985459965597c97c3759b44ed252b/testbuild \
build/.conf_check_293985459965597c97c3759b44ed252b \
build/.conf_check_114df6287ed99356d14a06682bc98197/testbuild \
build/.conf_check_114df6287ed99356d14a06682bc98197 \
build/.conf_check_0927534631877d46f179382e3e16c60a/testbuild \
build/.conf_check_0927534631877d46f179382e3e16c60a \
bindings/python \
.metadata/.plugins/org.eclipse.cdt.make.core \

